replicaCount: 1

namespace: flag

image:
  repository: 091565283934.dkr.ecr.us-east-1.amazonaws.com/flag-service
  pullPolicy: IfNotPresent
  tag: "72c1f84b010a5fee70a5bec5f6bbe8118f95d76e"

imagePullSecrets: []
nameOverride: "flag-service"
fullnameOverride: "flag-service"

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: ClusterIP
  # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  port: 8002
  targetPort: 8002

# This block is for setting up the ingress for more information can be found here: https://kubernetes.io/docs/concepts/services-networking/ingress/
ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: tooglemaster.com.br
      paths:
        - path: /flag
          pathType: Prefix
          backend:
            service:
              name: flag-service
              port:
                number: 8002


envVariables:
  PORT: "8002"
  AUTH_SERVICE_URL: "http://auth-service.auth.svc.cluster.local:8001"

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "1000m"
    memory: "512Mi"

# This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
livenessProbe:
  httpGet:
    path: /health
    port: 8002
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3
readinessProbe:
  httpGet:
    path: /health
    port: 8002
  periodSeconds: 5
