apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  namespace: targeting
type: Opaque
stringData:
  DATABASE_URL: "postgres://postgres:auth-service-postgres.c40i1rnmdkx9.us-east-1.rds.amazonaws.com:5432/postgres"
  MASTER_KEY: "admin-secreto-123"
