apiVersion: v1
kind: Secret
metadata:
  name: analytics-service-secret
  namespace: targeting
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "ASIARKUNXLJPG6ZALSPV"
  AWS_SECRET_ACCESS_KEY: "aVJBR3Cm9H7YF+FylZ5dkGdyhJ5CjYFXNoDTfhV1"
  AWS_SESSION_TOKEN: "IQoJb3JpZ2luX2VjEPD//////////wEaCXVzLXdlc3QtMiJHMEUCIQDL95TOxRPBge8c6xFpDzBFtBx1px2Ul9M3PTe4w9yLTQIgWevyd1EHHxkbxtsDqySzh209k1ij61XcnniuQ8W7wIQquAIIuf//////////ARAAGgwwOTE1NjUyODM5MzQiDMzIp8+MYKmCGDGLmSqMAtqg8tndGG5+YVWx4N38ArZ4JyeZ8SUchsvHwamsdZviMMRlmhTaPVXpG+2MnJOzbSG6f35UUoHm6O67FBlYmE0zXgEi++fVr11z76Xnjog5hbCW9rkVdolKeqwLhdW/NYpzrmvYWPPLuUb+77G0WLODDOt750NjbrFUTLjJzEaLqmUWXBsInfgTPi+cBcnyOlfVgpQVG7Zrj22fkg8qlMHqRSdThlvVcdPWyJ2lo+o1biD0gm2o0bxmQXhY3++O4u2YmfuGdJI2011oglCAmOk1LMNsMa7P0AoPjXdqaqhrDn9vC3X9XQGKDtUKwZ3fhgCazlMnY5l4HwGzIZqj4JMxYZjZDWgbJ4ySbmkwlPOV1QY6nQFxyyCiXpsYFfYmnkcEcw03aHi8q5u3FHAYfzen7qfFhh2PHbYfM8ky1R0+sE4QUU9/V5eKDDvNZ2BAYg1RMCRyeGxwbcivvWjxSSfcXlDegPQ52gggATpVdNIIta4La7Oy0JyKYEOFdKRBVpXg8tnFx5Ss93XyjGxL4YqM5rudVH/sefpsHaKbBIMQvzPZ+ibtWTuH9s+R9GFoED5b"